@startuml
left to right direction

' Actores Primarios (Izquierda - Inician la interacción en la interfaz)
actor Administrador
actor Residente

' Actores Secundarios (Derecha - Participan, asisten o reciben la acción)
actor "Personal de seguridad" as Seguridad
actor "Personal de mantenimiento" as Mantenimiento

rectangle "eBarrio" {
  usecase "Iniciar sesion" as UCLogin
  usecase "Gestionar residentes" as UCResidentes
  usecase "Crear cuenta de sistema" as UCCuenta
  usecase "Gestionar visitantes" as UCVisitantes
  usecase "Registrar ingreso" as UCIngreso
  usecase "Registrar egreso" as UCEgreso
  usecase "Crear reclamo" as UCReclamo
  usecase "Crear tarea de mantenimiento" as UCTarea
  usecase "Reportar incidente seguridad" as UCIncidente
  usecase "Avanzar estado de solicitud" as UCAvanzar
  usecase "Cancelar solicitud" as UCCancelar
  usecase "Consultar notificaciones" as UCNotificaciones
}

' --- RELACIONES ACTORES PRIMARIOS (De Izquierda a Derecha) ---
Administrador --> UCLogin
Administrador --> UCResidentes
Administrador --> UCIngreso
Administrador --> UCEgreso
Administrador --> UCIncidente
Administrador --> UCTarea
Administrador --> UCAvanzar
Administrador --> UCCancelar
Administrador --> UCNotificaciones

Residente --> UCLogin
Residente --> UCVisitantes
Residente --> UCReclamo
Residente --> UCNotificaciones

UCResidentes .> UCCuenta : <<include>>

' --- RELACIONES ACTORES SECUNDARIOS (Desde el Caso de Uso hacia la Derecha) ---
UCIngreso <-- Seguridad
UCEgreso <-- Seguridad
UCIncidente <-- Seguridad

UCTarea <-- Mantenimiento
UCAvanzar <-- Mantenimiento
@enduml